---
title: "Reproducible Research: Peer Assessment 1"
author: "David Bradford"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
 html_document:
   keep_md: true
   code_folding: hide
   toc: true
   toc_float: true
   theme: cosmo
---

```{r load packages, message=F, warning=F}
#library(ggplot2)
#library(dplyr)
#library(statsr)
library(data.table)
#library(ggplot2)
#library(grid)
#library(gridExtra)
#library(knitr)
#library(kableExtra)
#library(tidyverse)
```

## Loading and preprocessing the data

```{r}
# set working & create data directory
setwd("C:\\Users\\dabradford\\Desktop\\Coursera\\DataSci\\Reproducible\\Project - Week 2")
if(!file.exists("./data")){dir.create("./data")}

# download activity monitoring data
get.data.project <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
download.file(get.data.project,destfile="./data/activity_monitoring_data.zip",method="auto")

zipfile.data = "activity_monitoring_data.zip"

# make sure the data is in the working directory if not download the zip file into the to zipfile.data and unzip it
if(!file.exists(zipfile.data)) {        
    unzip(zipfile="./data/activity_monitoring_data.zip",exdir="./data")
} 

path_act <- file.path("./data" , "./data/activity_monitoring_data")
files<-list.files(path_act, recursive=TRUE)
files

# Read data files
activity <- data.table::fread("./data/activity.csv")

# inspect data file
#str(activity)
#head(activity)
```



## What is mean total number of steps taken per day?



## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?

